import torch
from torch.nn import Module
from contextlib import nullcontext
from utils.logits_processor import LogitsProcessor, GreedyProcessor
from transformers.cache_utils import DynamicCache
from utils.caching import prune_cache
import utils.printing as printing
from sampling.model_call import model_forward
from typing import List, Tuple


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


@torch.no_grad()
def speculative_generate(
    inputs: List[int],
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
    profiler = None,
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)
    
    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): whether to skip the sample adjustment step when some drafts are discarded.
        first_target (bool): whether to run the target model before the speculative algorithm.
        debug (bool): debug mode.
    
    Returns:
        List[int]: generated sequence.
        float: acceptance rate (number of accepted drafts divided by the number of total drafts).
        
    Note: This generation methods only works for decoder-only models.
    Note bis: The drafter and target models should output the same logits shape.
    Note ter: NgramModels are currently not supported.
    """
    
    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    drafts_accepted, drafts_speculated = .0, .0
    
    vocabulary_size = target.config.vocab_size    
        
    # prepare input tensor
    prompt_len = len(inputs)
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = torch.tensor(inputs, dtype=torch.long, device=target.device)
    
    current_position = prompt_len

    def _finish(end_position: int) -> Tuple[List[int], float]:
        output = input_ids[0, prompt_len:end_position].tolist()
        accept_rate = drafts_accepted / drafts_speculated if drafts_speculated > 0 else 0
        if profiler is not None:
            profiler.set_metric("generated_tokens", len(output))
            profiler.set_metric("drafts_accepted", int(drafts_accepted))
            profiler.set_metric("drafts_speculated", int(drafts_speculated))
            profiler.set_metric("acceptance_rate", accept_rate)
        return output, accept_rate
    
    if first_target:
        # run the target model before the speculative algorithm. Allows to prefill the kvcache and get a first token.
        Mp = model_forward(
            target,
            input_ids=input_ids[..., :current_position],
            past_key_values=target_cache,
            use_cache=use_cache,
            profiler=profiler,
            phase="target_forward",
            call_kind="initial",
            logits_start=current_position - 1,
            logits_end=current_position,
        )
        target_cache = Mp.past_key_values
        p_p = logits_processor(Mp.logits[..., -1, :])
        t = logits_processor.sample(p_p)
        input_ids[0, current_position] = t
        current_position += 1
        
        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return _finish(current_position)
        
        if debug:
            printing.initial_step(t, tokenizer)
    
    while current_position < total_len:
        corrected_gamma = min(gamma, total_len - current_position - 1)
        q = torch.zeros((1, corrected_gamma, vocabulary_size), device=target.device)
        
        input_ids = input_ids.to(drafter.device)
        
        # generate gamma drafts
        draft_timer = profiler.time(
            "drafter_generate",
            current_position=current_position,
            corrected_gamma=corrected_gamma,
        ) if profiler is not None else nullcontext()
        with draft_timer:
            for k in range(corrected_gamma):
                Mq = drafter(
                    input_ids=input_ids[..., :current_position + k],
                    past_key_values=drafter_cache,
                    use_cache=use_cache,
                )
                drafter_cache = Mq.past_key_values
                
                draft_logits = Mq.logits[..., -1, :]
                draft_probs = logits_processor(draft_logits)
                q[0, k] = draft_probs.to(target.device)
                xi = logits_processor.sample(draft_probs)
                input_ids[0, current_position + k] = xi
        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)
        
        # run target model on drafts and get logits of the previous tokens plus one more token
        Mp = model_forward(
            target,
            input_ids=input_ids[..., :current_position + corrected_gamma],
            past_key_values=target_cache,
            use_cache=use_cache,
            profiler=profiler,
            phase="target_forward",
            call_kind="verify",
            current_position=current_position,
            corrected_gamma=corrected_gamma,
            logits_start=current_position - 1,
            logits_end=current_position + corrected_gamma,
        )
        target_cache = Mp.past_key_values
        if getattr(target, "supports_logits_window", False):
            draft_logits = Mp.logits[..., :corrected_gamma, :] # [1, corrected_gamma, vocab_size]
        else:
            draft_logits = Mp.logits[..., current_position - 1:current_position + corrected_gamma - 1, :] # [1, corrected_gamma, vocab_size]
        p = logits_processor(draft_logits) # [1, gamma, vocab_size]
        
        # compute the last accepted draft position (rejection sampling)
        accept_timer = profiler.time(
            "acceptance_sampling",
            current_position=current_position,
            corrected_gamma=corrected_gamma,
        ) if profiler is not None else nullcontext()
        with accept_timer:
            r = torch.rand(corrected_gamma, device=target.device)
            fractions = p / q
            n = corrected_gamma
            for i in range(corrected_gamma):
                if r[i] > fractions[0, i, input_ids[0, current_position + i]]:
                    n = i
                    break
        
        drafts_accepted += n
        
        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return _finish(current_position + stop_location + 1)

        # adjust the distribution from Mp
        if n == corrected_gamma:
            if getattr(target, "supports_logits_window", False):
                p_p = Mp.logits[..., corrected_gamma, :]
            else:
                p_p = Mp.logits[..., current_position + corrected_gamma - 1, :]
            p_p = logits_processor(p_p)
        else:
            # prune the cache
            if use_cache:
                drafter_cache = prune_cache(drafter_cache, corrected_gamma - n)
                target_cache = prune_cache(target_cache, corrected_gamma - n + 1)
            
            if not skip_sample_adjustment:
                p_p = max_fn(p[..., n, :] - q[0, n, :])
            else:
                p_p = p[..., n, :]
        x = logits_processor.sample(p_p)
        
        if debug:
            generated = input_ids.clone().detach()
            
        input_ids[0, current_position + n:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + n] = x
        
        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)
            
        current_position += n + 1
        
        if torch.isin(x, stop_tokens):
            if debug:
                printing.end_token_found(n)
            return _finish(current_position)
    
    return _finish(total_len)


@torch.no_grad()
def speculative_generate_greedy_server_accept(
    inputs: List[int],
    drafter: Module,
    target,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    debug: bool = False,
    profiler = None,
) -> Tuple[List[int], float]:
    """Greedy edge-cloud speculative decoding with server-side verification.

    The target service returns only accepted_count and next_token_id, avoiding
    full-vocabulary logits downlink. This path is intended for greedy timing
    experiments and requires the remote target to implement verify_greedy().
    """
    if not hasattr(target, "verify_greedy"):
        raise ValueError("speculative_generate_greedy_server_accept requires a remote target with verify_greedy().")
    if use_cache:
        raise ValueError("Server-accept speculative mode does not support client-side KV-cache transfer.")

    drafter_cache = None
    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)

    drafts_accepted, drafts_speculated = 0.0, 0.0
    prompt_len = len(inputs)
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = torch.tensor(inputs, dtype=torch.long, device=target.device)
    current_position = prompt_len

    def _finish(end_position: int) -> Tuple[List[int], float]:
        output = input_ids[0, prompt_len:end_position].tolist()
        accept_rate = drafts_accepted / drafts_speculated if drafts_speculated > 0 else 0
        if profiler is not None:
            profiler.set_metric("generated_tokens", len(output))
            profiler.set_metric("drafts_accepted", int(drafts_accepted))
            profiler.set_metric("drafts_speculated", int(drafts_speculated))
            profiler.set_metric("acceptance_rate", accept_rate)
            profiler.set_metric("server_accept_mode", True)
        return output, accept_rate

    def _target_step(corrected_gamma: int, call_kind: str) -> dict:
        return target.verify_greedy(
            input_ids[..., : current_position + corrected_gamma],
            current_position=current_position,
            corrected_gamma=corrected_gamma,
            profiler=profiler,
            profile_metadata={"call_kind": call_kind},
        )

    # Initial target token. This keeps behavior comparable to the existing
    # speculative_generate(first_target=True) path while returning only one id.
    result = _target_step(0, "initial")
    first_token = torch.tensor([[result["next_token_id"]]], dtype=torch.long, device=target.device)
    input_ids[0, current_position] = int(result["next_token_id"])
    current_position += 1
    if torch.isin(first_token, stop_tokens):
        if debug:
            printing.end_token_found(0)
        return _finish(current_position)
    if debug:
        printing.initial_step(first_token, tokenizer)

    while current_position < total_len:
        corrected_gamma = min(gamma, total_len - current_position - 1)

        input_ids = input_ids.to(drafter.device)
        draft_timer = profiler.time(
            "drafter_generate",
            current_position=current_position,
            corrected_gamma=corrected_gamma,
            server_accept_mode=True,
        ) if profiler is not None else nullcontext()
        with draft_timer:
            for k in range(corrected_gamma):
                Mq = drafter(
                    input_ids=input_ids[..., :current_position + k],
                    past_key_values=drafter_cache,
                    use_cache=False,
                )
                drafter_cache = Mq.past_key_values
                draft_logits = Mq.logits[..., -1, :]
                draft_probs = logits_processor(draft_logits)
                xi = logits_processor.sample(draft_probs)
                input_ids[0, current_position + k] = xi

        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)

        result = _target_step(corrected_gamma, "verify_greedy")
        n = int(result["accepted_count"])
        drafts_accepted += n

        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return _finish(current_position + stop_location + 1)

        next_token = torch.tensor([[int(result["next_token_id"])]], dtype=torch.long, device=target.device)
        if debug:
            generated = input_ids.clone().detach()

        input_ids[0, current_position + n:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + n] = int(result["next_token_id"])

        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)

        current_position += n + 1
        if torch.isin(next_token, stop_tokens):
            if debug:
                printing.end_token_found(n)
            return _finish(current_position)

    return _finish(total_len)
